# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import requestsHandler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_hash', models.CharField(default='0dcd4038895f9799800bd3f0d62554d1f16720cc', max_length=40, unique=True)),
                ('private_hash', models.CharField(default='463269472cc99bb3ad134f1649a818dc44de65f3', max_length=40, unique=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('fields_cache', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('user', models.OneToOneField(default=requestsHandler.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
