# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='fields_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='7584ee6b9b67b08a846426278a907fb65cfef230', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='97e6f0269879688a1e1867f1d9342f76fb545300', max_length=40, unique=True),
        ),
    ]
