# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0002_auto_20171120_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='last_user_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='2e62a621d6c514080bb532681a124cd979b49660', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='38b5e180f4130d6487d07e97cec4074794891528', max_length=40, unique=True),
        ),
    ]
