# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0002_auto_20171118_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='user_hash',
            field=models.CharField(default='0fa78cf1a1eb3af58d8bd4a576585b', max_length=10, unique=True),
        ),
    ]
