# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0003_auto_20171118_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='user_hash',
            field=models.CharField(default='fd51ec3bc00d70a1fa9a710823a7d289ca9505b1', max_length=35, unique=True),
        ),
    ]
