# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 21:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestsHandler', '0003_auto_20171121_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserConfig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('public_hash', models.CharField(db_index=True, default='238352d0d60212a138a5ffc35431b71a859f346e', max_length=40)),
                ('private_hash', models.CharField(db_index=True, default='e49ab0f46816e75137c57c4c33e4dcc9d43ac06f', max_length=40)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('fields_cache', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('last_user_cache', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical user config',
            },
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='e49ab0f46816e75137c57c4c33e4dcc9d43ac06f', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='238352d0d60212a138a5ffc35431b71a859f346e', max_length=40, unique=True),
        ),
    ]
