# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 23:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0004_auto_20171230_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='90c06338a33a4bfbc296f692cdf72c68e94b1697', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='be51db9dc1fa6dac396f294e0d2df7843d357105', max_length=40),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='90c06338a33a4bfbc296f692cdf72c68e94b1697', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='be51db9dc1fa6dac396f294e0d2df7843d357105', max_length=40, unique=True),
        ),
    ]
