# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0004_auto_20171118_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='user_hash',
            field=models.CharField(default='9ec508fdb6654235b7eab721d85efd2edc5cab21', max_length=40, unique=True),
        ),
    ]
