# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 12:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0005_auto_20171230_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'paid_till': 1515241494.340993}),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cache_ttl': 300, 'hash': '', 'subdomain': '', 'user': ''}),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='efb33064a5314bec759b3aa16bba3823433509ea', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='832d2a94666a2aa47576886e7198eaa173f085d1', max_length=40),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'paid_till': 1515241494.340993}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cache_ttl': 300, 'hash': '', 'subdomain': '', 'user': ''}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='efb33064a5314bec759b3aa16bba3823433509ea', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='832d2a94666a2aa47576886e7198eaa173f085d1', max_length=40, unique=True),
        ),
    ]
