# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 12:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsHandler', '0006_auto_20180106_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'paid_till': 1517834908.371195}),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cache_ttl': 300, 'email': {}, 'hash': 'hash', 'jivo_site': {}, 'onpbx': {}, 'site_forms': {}, 'subdomain': 'subdomain', 'user': 'user'}),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='74675b51e9f2ac13beb21a7e8e7d1bcd734922a0', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaluserconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='09294b76127f2229e2d5b7c24d5e708e5818a247', max_length=40),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='account_rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'paid_till': 1517834908.371195}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cache_ttl': 300, 'email': {}, 'hash': 'hash', 'jivo_site': {}, 'onpbx': {}, 'site_forms': {}, 'subdomain': 'subdomain', 'user': 'user'}),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='private_hash',
            field=models.CharField(db_index=True, default='74675b51e9f2ac13beb21a7e8e7d1bcd734922a0', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='public_hash',
            field=models.CharField(db_index=True, default='09294b76127f2229e2d5b7c24d5e708e5818a247', max_length=40, unique=True),
        ),
    ]
